### ISSUE TITLE
Help wanted: Complete testing

### ISSUE THREAD

**Issue by anchepiece** [anchepiece/suggest#2]
Looking for examples that break the code or are possible edge cases where output is unexpected.

**Comment by vikashvverma** [comment]
@anchepiece I can help. As I see everything is tested. Apart from some minor issue which I have listed everything is tested. What else you want to tests?

**Comment by anchepiece** [comment]
Looks good! Thanks for the pull request. This issue is basically to flush out any real use issues. If you run into anything lets put a test in to check  for it.

Thanks!
