### ISSUE TITLE
Example showing usage in a web backend service

### ISSUE THREAD

**Issue by anchepiece** [anchepiece/suggest#3]
Looking for a simple example of usage in a web based system.

Something like a tags autocomplete that suggests an existing tag when a user misspells entries.

**Comment by dixonwille** [comment]
Do you want like an API endpoint? kind of tough just to show backend because you will need to set the front end to call the backend?

**Comment by anchepiece** [comment]
That's a good point, but it could work as an api endpoint that you can run curl against. Here is a command line based example: https://github.com/anchepiece/suggest-autocorrect  

That is how I am using this project, maybe just look at a simple http server based api that does the same thing.  Let me know if you want to jump in with an idea, we could always dump that example and a web based on into this repo directly.

**Comment by dixonwille** [comment]
@anchepiece Getting PR ready now for and API endpoint for curl.

**Comment by anchepiece** [comment]
Implemented in #8 - thanks!
